---
stages:
  - acceptance

## Uncomment the following sections to enable docker, image building and acceptance

# build:
#   stage: build
#   image: alpine:latest
#   artifacts:
#     paths:
#       - bin/
#   script:
#     - echo do something to build the binary or whatever

# build_image:
#   stage: docker
#   image: docker:latest
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#   services:
#     - docker:dind
#   script:
#     - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
#     - docker build . -t ${CI_REGISTRY_IMAGE}:latest
#     - docker push ${CI_REGISTRY_IMAGE}:latest

## Uncomment the acceptance step and do not remove, this step is required for us
## to accept your submission!

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  before_script:
    - apk add --no-cache py2-pip && pip install docker-compose
  script:
    - docker-compose up -d
    - /harness --address http://pooling:9091 acceptance
