image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
#  CI_REGISTRY: registry.gitlab.com
#  CI_REGISTRY_IMAGE: $CI_REGISTRY/cabify-challenge/car-pooling-challenge-mariocs
#  CI_REGISTRY_USER: gitlab-deploy-token-1
#  CI_JOB_TOKEN: UCDoFwDGqKcFZXGMrQ5L

services:
  - docker:dind

stages:
  - build
  - test
  - acceptance

build:
  stage: build
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:latest

acceptance:
  stage: acceptance
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker-compose up --abort-on-container-exit --exit-code-from harness


---
# stages:
#   - docker
#   - acceptance

# ## Uncomment the following sections to enable docker, image building and acceptance

# # build:
# #   stage: build
# #   image: alpine:latest
# #   artifacts:
# #     paths:
# #       - bin/
# #   script:
# #     - echo do something to build the binary or whatever

# build_image:
#   stage: docker
#   image: docker:latest
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#   services:
#     - docker:dind
#   script:
#     - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
#     - docker build . -t ${CI_REGISTRY_IMAGE}:latest
#     - docker push ${CI_REGISTRY_IMAGE}:latest

# ## Uncomment the acceptance step and do not remove, this step is required for us
# ## to accept your submission!

# acceptance:
#   image: cabify/challenge:latest
#   stage: acceptance
#   services:
#     - name: ${CI_REGISTRY_IMAGE}:latest
#       alias: pooling
#   only:
#     - master
#   dependencies: []
#   script:
#     - /harness --address http://localhost:9091 acceptance
